# This is a basic workflow to help you get started with Actions

name: CI/CD dev

on:
  push:
    branches: [ dev ]

  workflow_dispatch:

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
  publish:
    name: Publish to Docker Hub
    if: github.repository == 'suleimant/pai' && github.ref == 'refs/heads/dev'
    uses: ./.github/workflows/publish_docker.yml
    needs: test
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
