name: Release

on:
  release:
    types: [published]

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
  publish_docker:
    name: Publish to Docker Hub
    uses: ./.github/workflows/publish_docker.yml
    needs: test
    if: github.repository == 'suleimant/pai'
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

